image: Visual Studio 2017
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
    - master
nuget:
    disable_publish_on_pr: true
build_script:
- ps: ./Build.ps1
artifacts:
    - path: .\artifacts\**\*.nupkg
        name: NuGet
deploy:
    provider: NuGet
    api_key:
        secure: KzSuFGmTy+u9GRlHlfVHdFEsFfj7/3XzfxotzyxNZ4B5WEj8XYIzYnU84MZPBVFE
    skip_symbols: false
    artifact: .\artifacts\**\*.nupkg
    on:
        branch: master
